#!/bin/bash
# Preparation:
rootPath="./"
confFile="conf.d/leapond.ca.cnf"
tmpPath="CA/"
outPath="output/"
outFile="leapondCA"
outExt=".crt"

echo "####################################"
echo "Generating OpenSSL Root CA."
echo "####################################"

if ! [ -e $tmpPath ] ; then
  mkdir $tmpPath"tmp" -p
  echo ""
  echo "The output directory not existed, auto created."
fi

if ! [ -e $confFile ] ; then
  echo ""
  echo "The Root CA config file not existed!"
  while read -p "Continue without config file? (y/n):" overwrite
    do
      case $overwrite in
        Y|y|yes)
          echo ""
          echo -e "Start generating without config file."
          break;
          break;
        ;;
        N|n|no)
          echo ""
          echo -e "Skipped for missed config file."
          exit 0
        ;;
        *)
          #echo -e "Wrong input!"
          continue
      esac
  done
fi

if [ -e $outPath$outFile$outExt ] ; then
  echo "The Root CA file ($outPath$outFile$outExt) already existed!"
  while read -p "Overwrite existed CA file? (y/n):" overwrite
    do
      case $overwrite in
        Y|y)
          echo -e "Forced to overwrite the exited Root CA."
          break;
          break;
        ;;
        N|n)
          echo -e "Skipped to overwrite exited Root CA."
          exit 0
        ;;
        *)
          #echo -e "Wrong input!"
          continue
      esac
  done
fi
openssl genrsa -out $outPath$outFile.key 4096 -des3
# Self sign
openssl req -x509 -new -nodes -key $outPath$outFile.key -days 3653 -out $outPath$outFile$outExt -config $confFile $@
